### ISSUE TITLE
Further development of the addon. Is it alive?

### ISSUE THREAD

**Issue by Tonedus** [fedackb/yavne#17]
Does this addon continue to be developed? For me it is a damn useful addon that has saved my life many times! Are there any plans to improve and develop this wonderful addon?

**Comment by Berandas** [comment]
I would second this, I find this addon essential for my workflow, yet now with Blender 4.1 out it does not work anymore.

**Comment by Tonedus** [comment]
> I would second this, I find this addon essential for my workflow, yet now with Blender 4.1 out it does not work anymore.

Do you know how to contact the developer? He hasn't been here for a while.

**Comment by Berandas** [comment]
Sadly no, I feel that the best chance might be to try finding someone who would be able to fork this and get it working with Blender 4.1 ... 🤷‍♂️

**Comment by JordanRO2** [comment]
> Sadly no, I feel that the best chance might be to try finding someone who would be able to fork this and get it working with Blender 4.1 ... 🤷‍♂️

Is this add-on actually that useful? I would give it a try

**Comment by Berandas** [comment]
> Is this add-on actually that useful?

I assume all of its functions can be done manually, it's just super-tedious and time consuming, while with the addon it's a single-click operation, so my answer to that would definitely be yes.
The issue is related to how the sharp edges are handled, which has changed in 4.1.

**Comment by JordanRO2** [comment]
I've completed a functional version for Blender 4.2 (it might also work for 4.1). Feel free to check it out. I created a pull request (#18) with the updates.

**Comment by Berandas** [comment]
Sir, you are a hero!
I just tested it with Blender 4.2 and it seems to be working perfectly fine again (for my workflow at least). The only thing I was first confused about is the automatic addition of "!!Auto Smooth" modifier, which broke the shading – it took me some time to figure out that the modifier was added and I need to disable/remove it in order to fix it, perhaps having some message mentioning that a modifier was added would help with the UX here.
![01](https://github.com/user-attachments/assets/0dd69113-348f-4edd-8342-631dd094da4e)
![02](https://github.com/user-attachments/assets/a3dadc1b-8752-463d-99f3-f44f63e25034)

Let's see if you get some more feedback, but so far you did a great job, thank you! ;-)

**Comment by Tonedus** [comment]
> this add-on actually that useful? I would

That would be great! This addon is so damn useful! It handles the result much better than the built-in tools in Blender.

**Comment by Berandas** [comment]
Been using it for several months now, and everything seems to be working okay for me. Big thanks to @JordanRO2 again. ;-)

**Comment by ranaragua** [comment]
@JordanRO2 
thanks for the update, but my blender 4.2.3 throw back 2 errors

the first one is
'Mesh' object has no attribute 'use_auto_smooth'
I just deleted the 2 lines with the phrase

then the second one is
name 'math' is not defined
so I added a "import math" line

now the tool works fine but I'm not sure if it's OK to do the first edit.

**Comment by MaximumYoba** [comment]
I think it cool addon, but im always get this error:

Python: Traceback (most recent call last):
File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\yavne-master\operators.py", line 174, in execute bpy.ops.mesh.yavne_update_vertex_normals ()
File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call____
ret = _op_call(self.idname_py(), kw)
ΑΑΑΑΑΑ
^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\yavne-master\operators.py", line 980, in execute mesh.use_auto_smooth = True
ΑΑΑΑΑΑΑΑΑΑΑΑΑΑΑΑΑΑΑΑ
AttributeError: 'Mesh' object has no attribute 'use_auto_smooth'
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109

Please, help me to fix this

**Comment by MaximumYoba** [comment]
@JordanRO2 @ranaragua I think it cool addon, but im always get this error:

Python: Traceback (most recent call last):
File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\yavne-master\operators.py", line 174, in execute bpy.ops.mesh.yavne_update_vertex_normals ()
File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call____
ret = _op_call(self.idname_py(), kw)
ΑΑΑΑΑΑ
^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\yavne-master\operators.py", line 980, in execute mesh.use_auto_smooth = True
ΑΑΑΑΑΑΑΑΑΑΑΑΑΑΑΑΑΑΑΑ
AttributeError: 'Mesh' object has no attribute 'use_auto_smooth'
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109

Please, help me to fix this

**Comment by MaximumYoba** [comment]
I found this thing. just replace line 980 to

```
if hasattr(mesh, 'use_auto_smooth'):
    mesh.use_auto_smooth = True
elif hasattr(mesh, 'auto_smooth_enabled'):
    mesh.auto_smooth_enabled = True
```

**Comment by Berandas** [comment]
The new Blender 4.3 makes this addon not working for me again.
@JordanRO2 Could I bother you some more?

**Comment by JordanRO2** [comment]
> The new Blender 4.3 makes this addon not working for me again.
> @JordanRO2 Could I bother you some more?

Kinda busy this week but gonna work on it during the weekend 👍

**Comment by Berandas** [comment]
> Kinda busy this week but gonna work on it during the weekend 👍

Happy new year...and also...bump. ;-)

EDIT: I noticed that after updating some official addons through Blender I am no longer getting errors while using YAVNE in 4.3.2, so it might have been a conflict with something else.

**Comment by ashleydevelops** [comment]
I still have the same auto_smooth error even after using the branch version. Can anyone help please? :(

(I'm using LTS 4.2.11)

EDIT: Welp I seemed to have fixed it by changing (on the operators.py)


`mesh.use_auto_smooth = True`

to 

`mesh.shade_smooth()`

**Comment by Berandas** [comment]
Anyone got this working with Blender 4.5, or found any alternative?

**Comment by JordanRO2** [comment]
@Berandas @Tonedus @ranaragua @MaximumYoba @ashleydevelops 

Updated the addon for Blender 4.5+ 

All the errors you mentioned are fixed - no more `use_auto_smooth` issues, math import is fixed, and it works with 4.5.1 LTS.

PR #18 is updated with all the fixes. You can grab it from my fork in the meantime: https://github.com/JordanRO2/yavne

Tested all operators and everything works fine. Let me know if you run into any issues!

**Comment by Berandas** [comment]
@JordanRO2 You're a lifesaver again, thank you very much! Just tested on 4.5.1 Win64 and everything seems to be working flawlessly.

**Comment by JordanRO2** [comment]
> [@JordanRO2](https://github.com/JordanRO2) You're a lifesaver again, thank you very much! Just tested on 4.5.1 Win64 and everything seems to be working flawlessly.

See you the next year during august 🥸
